- lib/rtc_peerconnection.dart
`onIceConnectionState` and `onIceGatheringState` wasn't called when `onSignalingState` is null
> Fixed few callbacks not called

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
Fixed the NPE by adding a null check. Tested manually.
> Fixed issue #29: Android: getUserMedia does not work for capturing audio only

- ios/flutter_webrtc.podspec
I found the corresponding command than needs to be added to the podspec file here: http://guides.cocoapods.org/syntax/podspec.html#static_framework
After this change, I was able to compile my project with `use_frameworks!`. I also verified that the example project compiles and runs if I add `use_frameworks!` to its Podfile.
> Fixed issue #49: The plugin is incompatible with use_frameworks in Podfile

- lib/rtc_peerconnection_factory.dart
Seems like the entire function after line 9 was indentated by an extra level, this patch fixes that and some other minor whitespace things ☺️
> Fix indentation in peer connection factory

- example/lib/src/get_user_media_sample.dart
- ios/Classes/FlutterRTCFrameCapturer.h
- ios/Classes/FlutterRTCFrameCapturer.m
- ios/Classes/FlutterRTCMediaStream.h
- ios/Classes/FlutterRTCMediaStream.m
- ios/Classes/FlutterWebRTCPlugin.m
This adds support for the `captureFrame` API, which previously was only available on Android, to iOS 🚀
> Add captureFrame support for iOS

- ios/Classes/FlutterRTCVideoRenderer.m
Fixes the following error:
```
error: property '_isFirstFrameRendered' not found on object of type 'FlutterRTCVideoRenderer *'; did you mean to access instance variable '_isFirstFrameRendered'?
self._isFirstFrameRendered = false;
~^
```
> Fix self property access in video renderer

- ios/Classes/FlutterRTCVideoRenderer.h
Fixes the following warning:
```
ios/Classes/FlutterRTCVideoRenderer.m:13:17: warning: method definition for 'initWithSize:' not found [-Wincomplete-implementation]
@implementation FlutterRTCVideoRenderer {
^
In file included from ios/Classes/FlutterRTCVideoRenderer.m:1:
ios/Classes/FlutterRTCVideoRenderer.h:18:1: note: method 'initWithSize:' declared here
- (instancetype)initWithSize:(CGSize)renderSize;
^
```
> Fix signature in FlutterRTCVideoRenderer header

- example/lib/src/data_channel_sample.dart
- lib/rtc_data_channel.dart
Map lookups should be faster than string comparisons, so this will likely improve performance.
This will change the API (again) but it will also make it safer, since the compiler will notify you if you mistype the identifier as an enum.
I also did some slight reformatting elsewhere in the file.
> Change datachannel message type identifier from a string to an enum, and remove it altogether from the send method and message listener.

- ios/Classes/FlutterRTCDataChannel.m
- ios/flutter_webrtc.podspec
See https://bugs.chromium.org/p/webrtc/issues/detail?id=10588
Yeah, it's hacky, if anyone has better solution - welcome
We could use label instead, but developers tend to use the same label for all data channels
Or we will be stuck with current WebRTC version
> Workaround for WebRTC issue 10588

- example/lib/src/data_channel_sample.dart
- lib/rtc_data_channel.dart
This change adds a streaming API to the `RTCDataChannel`. Adds `stateChangeStream` and `messageStream` to the `RTCDataChannel` class, which are broadcast streams that emit state changes and messages, just as would be passed to the `onDataChannelState` and `onMessage` handlers. This allows for easily attaching multiple listeners to these events, whereas previously the class could only support one handler for each. 
Adds functionality from my own wrapper utility class:
```dart
class StreamingRTCDataChannel {
RTCDataChannel dataChannel;
final _messageController = StreamController<RTCDataChannelMessage>.broadcast();
final _stateChangeController = StreamController<RTCDataChannelState>.broadcast();
Stream<RTCDataChannelMessage> message;
Stream<RTCDataChannelState> stateChange; …
```
> Add streaming API for datachannel messages and state changes.

- pubspec.yaml
(reverts #143, fixes #147)
On Flutter 1.10 and above, you can't mix legacy plugin definitions with the newer format (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/plugins.dart#L186-L192)
This PR removes the old style plugin definitions which breaks Flutter 1.9 and below. If it's merged, the plugin version should probably be bumped to `0.2.0`.
> Remove legacy plugin definitions

- ios/flutter_webrtc.podspec
The latest release of GoogleWebRTC requires ios platform 10.0
https://github.com/CocoaPods/Specs/blob/master/Specs/2/c/6/GoogleWebRTC/1.1.29400/GoogleWebRTC.podspec.json
I've opened a PR in the demo repository as well to match this https://github.com/cloudwebrtc/flutter-webrtc-demo/pull/63
> chore(ios): upgrade GoogleWebRTC dependency

- README.md
It is causing an issue on pub.dev where you can't see the path https://pub.dev/packages/flutter_webrtc
> docs(readme): missing back tick

- ios/flutter_webrtc.podspec
Fixes #168 
Created my own fork which uses same binary as https://github.com/waitingsnow/libyuv-iOS/ with updated headers. Tested on example project + our production app.
> Replace Libyuv dependency, fixing #168

- ios/Classes/FlutterRTCVideoRenderer.m
Currently `didTextureChangeVideoSize` event generates permanently when iOS device in portrait orintation.
> [iOS] Fix typo in render size change check condition

- lib/rtc_video_view.dart
- lib/web/rtc_video_view.dart
Currently used [deactivate](https://api.flutter.dev/flutter/widgets/State/deactivate.html) method can be called many times during a state lifecycle.
(For example, it called several times during animation, which occurs when `Scaffold` with
`RTCVideoView` is shown with regular route push animation.)
Actually, subclasses should override `deactivate` method to clean up any links between
this object and other elements in the tree (e.g. if you have provided an ancestor with
a pointer to a descendant's RenderObject). _/ adapted quote from [State objects lifecycle](https://api.flutter.dev/flutter/widgets/State-class.html)_
> Use proper state lifecycle method for nulling renderer state changed handler

- macos/Classes/FlutterRTCMediaStream.m
If RTCVideoView with opened _localRenderer placed at root Widget, after hot restarting application was crashed with error:
*** Assertion failure in -[RTCCameraVideoCapturer dealloc], ../../sdk/objc/components/capturer/RTCCameraVideoCapturer.m:113
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Session was still running in RTCCameraVideoCapturer dealloc. Forgot to call stopCapture?'
> [macOS] Fix hot restart videoCapturer crash

- lib/rtc_peerconnection_factory.dart
As we have default constraints in _createPeerConnection()_ we could make that arg optional in order to avoid passing empty map as following:
```dart
final pc = await createPeerConnection(configuration);
```
instead of: 
```dart
final pc = await createPeerConnection(configuration, {});
```
> Make optional 'constraints' argument in createPeerConnection()

- android/build.gradle
- android/proguard-rules.pro
It seems that instead of manually adding necessary for Flutter WebRTC ProGuard rules (as was suggested in [this comment](https://github.com/cloudwebrtc/flutter-webrtc/issues/205#issuecomment-601541102)), they could be added automatically with [library module ProGuard configuration file](https://developer.android.com/studio/projects/android-library) (and as result fix #205).
> Add library module ProGuard configuration file

- lib/web/rtc_video_view.dart
This commit fixes the case where multiple RTCVideoRenderer objects present on the same Flutter Web HTML page and where another object was using ui.platformViewRegistry.registerViewFactory() method.
This PR is supposed to fix issue #259 .
> Fixing multiple video renderers on the same HTML page for Flutter Web

- lib/rtc_data_channel.dart
The https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel specification provides read-only label for the data channel. Added a getter to get the label
> Added label as read only property

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
Fix for Android error:
Unable to getSources: Unsupported value: com.cloudwebrtc.webrtc.utils.ConstraintsArray@13ceca6#0
> fix android getsources error

- example/lib/src/loopback_sample.dart
- lib/src/rtc_dtmf_sender.dart
The api call is name insertDTMF
https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender/insertDTMF
renamed to function call to match with the WebRTC Api.
> Updated rtc_dtmf_sender

- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
This pull request fixes the following issues:
In unified-plan when calling `mediaStream.removeTrack(sender.track)` it throws track is null error because the track id is null as in the Java code it is called `trackId` while in Dart code it anticipates `id`.
And also in `peerConnection.removeTrack(sender)` it throws sender is null issue because in the java code the track id is compared with the `==` operator which compares reference instead of equality, it is replaced with the `.equals()` method to fix this issue.
I have created the issue here https://github.com/flutter-webrtc/flutter-webrtc/issues/400
> [Android] Fixed `Track is null` 'Sender is null' issues when removing track.

- common/darwin/Classes/FlutterRTCPeerConnection.m
- common/darwin/Classes/FlutterWebRTCPlugin.m
This pull request is for two issues:
1. The `removeTrack`method in `rtc_peerconnection_impl.dart` anticipates a boolean in `Map` with `result` as a key
```dart
bool result = response['result'];
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; but the `removeTrack` in Darwin's sends `nil` which throws `The Method '[ ]' was called on null "result"` in Dart.
2. The second issue was not registering `stream` and `track` in `onTrack` for `PeerConnection` - `didAddReceiver` in `Obj-c` - which results into a `Not found video track for RTCMediaStream: {streamId}` error.
______________________
Related issues: 
1. https://github.com/flutter-webrtc/flutter-webrtc/issues/402
2. https://github.com/flutter-webrtc/flutter-webrtc/issues/403
> [iOS] fix removeTrack methodChannel response, onTrack's `stream` and `track` not being registered in native.

- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
- common/darwin/Classes/FlutterWebRTCPlugin.m
- lib/src/native/rtc_peerconnection_impl.dart
This pull request fixes the following issues:
In unified-plan when calling `RTCRtpSender.setParameters(parameters)` it throws `Unsupported value` error because the value being sent is `null` as in native code `mapToRtpParameters` returns `null`.
Creating `RtpParameters` from a map is not easy as there is no constructor for some of its properties, and setting the parameter is mainly targeted towards encodings.
So `mapToRtpParameters` is replaced with `updateRtpParameters` to update the values of the sender's parameters (encodings only as the rest is read-only) with the values sent from Dart through the method channel.
Related issue: https://github.com/flutter-webrtc/flutter-webrtc/issues/405
> [Darwin/Android] `RtpSender` `setParameters` functionality.

- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
While debugging transceiver api in android, I found two small bugs in string compares.
There are still some problems in transceiver api, but this is a start.
> fix java string compare

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
- common/darwin/Classes/FlutterRTCPeerConnection.m
- common/darwin/Classes/FlutterWebRTCPlugin.m
when the remote end is using stage 3 of the evolution of tracks (see https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/) and using transceivers.  
`var t = pc.addTransceiver("video", { direction : 'inactive'});`
and then at a later time adding a track to the sender
```
t.direction = "sendonly";
t.sender.replaceTrack(track);
```
Streams are not used so I needed to add this code so as to be able to display the track in the video renderer.
I've had to make a local stream, add the track to it, which meant going and finding it in the transceiver.  Then the video renderer can take the new local stream and play the track.
> Unified plan gettracks

- android/src/main/java/com/cloudwebrtc/webrtc/utils/RTCAudioManager.java
- android/src/main/java/com/cloudwebrtc/webrtc/utils/RTCBluetoothManager.java
- common/darwin/Classes/FlutterWebRTCPlugin.m
This is a quick fix to enable Bluetooth switching on iOS and fix the issue where setting `enableSpeakerphone` to false would default to the phone (call) speaker even if a Bluetooth headset is connected.
This would fix the #201 issue, we aren't able to pick devices though.
> Bluetooth switching enabled when switching `enableSpeakerphone`  value (if they are connected). #201

- windows/src/flutter_peerconnection.cc
switch signalingState & iceConnectionState event name sink back to flutter on Windows platform
> fix signalingState & iceConnectionState event name

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
我看了下报错处的代码，并参照网上的代码做了修改，经过多次测试，没有再出现“getDisplayMedia只有第一次成功后面失败，报错user revoked permission”的问题。这个问题并不是稳定复现，但概率比较高。测试设备华为p30 android10，华为mate8 android 7。
> Getting screen content can only be successful for the first time

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/OrientationAwareScreenCapturer.java
Added `OrientationAwareScreenCapturer` which extends from `ScreenCapturerAndroid` but checks orientation in the `onFrame` and calls `changeCaptureFormat` if orientation changes, I don't know if it's the best approach since we call `windowManager.getDefaultDisplay().getRotation()` with each frame being processed but it works perfectly when I tested it out.
This is a fix to issue #495
> [Android] Screen share orientation fix #495 .

- common/darwin/Classes/FlutterWebRTCPlugin.m
Fix incorrect syntax in private api in `RTCConfiguration` in `FlutterWebRTCPlugin.m` causing app crashes in Darwin devices.
This should fix issue #565
> [Darwin] Fix incorrect syntax in private api in `RTCConfiguration` #565

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
Added code to fall back to the first available camera in case the `createVideoCapturer` fails to find a suitable camera based on constraints (doesn't have a front/back camera) like an Android TV that will most likely have an external camera or any other type.
> [Android] falling back to the first available camera fix #580

- android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java
When application exits, it throws an exception:
Exception 'java.lang.NullPointerException' occurred in thread 'main' at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.onDetachedFromActivity(FlutterWebRTCPlugin.java:97)
See also issue #578
Signed-off-by: Peter Antoniac <pan1nx+flutterwebrtc@gmail.com>
> Fix application exit null-pointer exception

- lib/src/interface/rtc_data_channel.dart
- lib/src/native/rtc_data_channel_impl.dart
- lib/src/web/rtc_data_channel_impl.dart
Adds a label getter to the DataChannel Interface and implements the label getter for the web implementation.
Closes #584
> Add label getter to DataChannel Interface

- lib/src/web/rtc_peerconnection_impl.dart
- lib/src/web/rtc_rtp_sender_impl.dart
Web implementation of `RTCPeerConnection .removeTrack` and `RTCRtpSender.setParameters` raises following exception. 
> Expected a value of type 'FutureOr<bool>', but got one of type 'Null' 
Actually, at the javascript implementation, type of the return value of these two functions is `void`, but implementation of `RTCPeerConnection .removeTrack` and `RTCRtpSender.setParameters` are assuming that the return type is `bool`.
To prevent this exception, I changed these two functions to ignore the return value came from javascript version of the function and just return a `true`.
> [Web] fix: exception raises at RTCPeerConnection and RTCRtpSender

- common/darwin/Classes/FlutterWebRTCPlugin.m
At the implementation of `RTCRtpSender` for Darwin, following method expects `senderId` argument. 
- `replaceTrack`
- `setTrack`
- `dispose`
But, implementation of  `RTCRtpSenderNative`, at  `rtc_rtp_sender_impl.dart`, called these methods with `rtpSenderId` argument. 
Because of this mismatch, these three method always raised exception with `Error: sender not found!` message.
I fixed the name of argument to `rtpSenderId` at the implementation of `RTCRtpSender` for Darwin.
> [Darwin] fix incorrect argument name at RTCRtpSender

- lib/src/web/media_stream_track_impl.dart
The current implementation of captureFrame works in debug mode but fails in
profile and release mode with `TypeError: ... is not a function`. This commit
uses js.callMethod to invoke the method instead of using the native api, which
seems to resolve this issue.
Fixes #621
> [web] Switch transferFromImageBitmap to be invoked using js.callMethod

- lib/src/web/rtc_video_renderer_impl.dart
> web: properly cleanup srcObject to avoid accidental dispose

- lib/src/web/rtc_video_renderer_impl.dart
When a single video renderer is removed, it removes the entire audio manager div, causing all audio tracks to stop playback.
> web: avoid removing all audio elements when stopping a single video renderer

- .gitignore
- lib/src/interface/media_stream_track.dart
- lib/src/web/media_stream_track_impl.dart
- lib/src/web/rtc_peerconnection_impl.dart
- lib/src/web/rtc_rtp_transceiver_impl.dart
- Added `MediaStreamTrack.getSettings` for Web
- `RTCPeerConnection.addTransceiver` for Web uses `track` instead of `kind` when both are specified.
> Web related fixes

- lib/src/web/rtc_video_renderer_impl.dart
Changing the audio output results in an error because the search element in audioOutput () is done with findHtmlView () and you need to use _audioElement
> Bug fix audioOutput()

- common/darwin/Classes/FlutterRTCMediaStream.m
- common/darwin/Classes/FlutterWebRTCPlugin.m
Fixing issues observed with original PR #705. This allows us to enable mic permissions much earlier on, regardless of how the user publishes the track.
> Enable audio capture when acquiring track

- lib/src/web/media_stream_impl.dart
- lib/src/web/media_stream_track_impl.dart
- lib/src/web/rtc_video_renderer_impl.dart
I believe the developer should be responsible of stopping tracks if required. Since tracks maybe required for later use.
This matches the behavior with iOS/Android, not calling `stop` on tracks when disposing `MediaStream`.
Additionally, `RTCVideoRendererWeb` shouldn't call `dispose` on `srcObject`. Any time `RTCVideoRendererWeb` gets disposed `srcObject` will get disposed.
I found that `MediaStreamTrack.dispose` is deprecated anyway :
https://github.com/flutter-webrtc/flutter-webrtc/blob/42940fb6f54e1e1ab170e4d66a987383f573d114/lib/src/interface/media_stream_track.dart#L115-L116
I agree `stop` should be called by developer whenever required.
@cloudwebrtc  @davidzhao
> Web: Don't stop tracks when disposing `MediaStream`

- common/cpp/src/flutter_peerconnection.cc
Windows 中的 onRemoveTrack 缺少参数。
> [Windows]为兼容目前的Flutter 的onRemoveTrack处理方式,添加必要参数

- example/lib/main.dart
Example app currently only initializes FlutterBackground, and doesn't actually start it.
> Properly start foreground service in example

- lib/src/media_devices.dart
> Fix typo in deprecated annotations

- common/darwin/Classes/FlutterRTCFrameCapturer.h
- common/darwin/Classes/FlutterRTCFrameCapturer.m
- common/darwin/Classes/FlutterRTCMediaStream.m
This pull request fixes the screen capture feature on IOS.
Additionally, IOS now supports screen captures for remote streams; this was previously not possible.
Changes are based on discussion here https://groups.google.com/g/discuss-webrtc/c/ULGIodbbLvM.
Fixes issues #765 and #635.
The previous code was using a deprecated (now removed) API of the WebRTC-SDK.
> Fix IOS captureFrame and add support for remote stream captureFrame

- common/cpp/src/flutter_webrtc_base.cc
Code was expecting a stun value to be under key 'url'.
I have added support for format of stun where url is just a string.
Diff is not good, because most of the code is actually not changed (just inserted inside if block).
> Fix parsing stun configuration

- common/cpp/src/flutter_media_stream.cc
There was no response to trackDispose method call.
That causes failure in client code and therefore not working mute.
> [windows] Fix mute

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/utils/ConstraintsMap.java
- android/src/main/java/com/cloudwebrtc/webrtc/utils/MediaConstraintsUtils.java
- common/cpp/src/flutter_media_stream.cc
- common/darwin/Classes/FlutterRTCMediaStream.m
Updating getUserMedia to use latest video constraint syntax (https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints).
Current getUserMedia constraints have been deprecated for years (and documentation is very sparse), so we should start looking to support the latest syntax.
> New video constraints syntax

- common/cpp/include/flutter_peerconnection.h
- common/cpp/src/flutter_peerconnection.cc
- common/cpp/src/flutter_webrtc_base.cc
- lib/src/web/rtc_video_renderer_impl.dart
- lib/src/web/rtc_video_view_impl.dart
In FlutterWebRTCBase::MediaTrackForId only local tracks were looked in.
Added also looking in remote tracks.
The problem was visible as described. When joining a session and trying to enable a track inside flutter_webrtc there is a call
`RTCMediaTrack* track = MediaTrackForId(track_id);`
That returned `nullptr` and exception was thrown:
`result->Error("mediaStreamTrackSetEnableFailed", "mediaStreamTrackSetEnable() track is null");`
> Fix issue with getting remote track

- common/cpp/src/flutter_media_stream.cc
Check if capturer is null and do not start video source
in that case.
> Fix crash on windows when camera is busy

- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
- common/darwin/Classes/FlutterWebRTCPlugin.m
- `rid` is missing for `rtpParametersToMap` for both iOS, Android.
- higher priority for updating encoding with same rid. (order of array wouldn't matter)
@davidzhao
> Better handling of `rid` in `sender.parameters.encodings`

- lib/src/native/rtc_peerconnection_impl.dart
- lib/src/native/rtc_rtp_sender_impl.dart
After following APIs are called, the 'track' property of the RTCRtpSender object was not updated. 
- `RTCRtpSender.setTrack()`
- `RTCRtpSender.replaceTrack()`
- `RTCPeerConnection.removeTrack()`
I fixed to correctly update the 'track' property of RTCRtpSender after processing these APIs.
> Properly change 'track' property of RTCRtpSender

- common/cpp/src/flutter_media_stream.cc
Greetings! Found next comment in `FlutterMediaStream::GetUserAudio()`: 
> TODO: Select audio device by sourceId
In the needs of my project, I implemented this functionality:
Passing media constraints with node 
`audio: { deviceId: 'some-device-id }` 
-- will select playback device; 
as well passing constraints with node 
`audio: { optional: [ { sourceId: 'another-device-id' } ]`
-- will select input device.
In addition was fixed problem of mixing up `deviceId` and `label` in results of `GetSources()` function.
Note than I'm a C++ beginner but this changes was tested and works.
Best regards
> [Windows] Feature of selecting i/o audio devices by passing sourceId and/or deviceId constraints

- README.md
I think minSdkVersion 23 is correct now, right?
> chore: Update minSdkVersion to 23 in readme

- android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java
The bug was  described in the #415 Issue. I have found the reason and have fixed the bug.
Also I have created a [demonstration app](https://github.com/mishkov/demonstrate_webrtc_leak). That repo has 2 branches `fixed-capture` and `broken-capture` read README.me to get guide how to checkout.
> Fix captureFrame on Android

- android/build.gradle
Switch to mavenCentral() in build.gradle because "jcenter()" (jcenter.bintray.com) servers are down from now.
> Update build.gradle - switch from jCenter to mavenCentral

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
Previously if something unexpected happened the flow calls `resultError()` then calls `result.success()` which throws "Reply already submitted" because result is already called inside `resultError()`.
> fix: "Reply already submitted" error and setVolume() not working on remote streams

- README.md
Simple formatting improvement.
Added a space above "## Functionality" so Markdown is displayed properly.
> Fix Markdown in ReadMe

- android/src/main/java/com/cloudwebrtc/webrtc/DataChannelObserver.java
- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
- common/cpp/include/flutter_data_channel.h
- common/cpp/include/flutter_webrtc_base.h
- common/cpp/src/flutter_data_channel.cc
- common/cpp/src/flutter_peerconnection.cc
- common/cpp/src/flutter_webrtc.cc
- common/darwin/Classes/FlutterRTCDataChannel.h
- common/darwin/Classes/FlutterRTCDataChannel.m
- common/darwin/Classes/FlutterRTCPeerConnection.h
- common/darwin/Classes/FlutterRTCPeerConnection.m
- common/darwin/Classes/FlutterWebRTCPlugin.m
- lib/src/native/rtc_data_channel_impl.dart
- lib/src/native/rtc_peerconnection_impl.dart
- test/unit/rtc_peerconnection_test.dart
We're using the data channel id as our internal id, but those ids may change if they get negotiated in-band, and causes issues locating the data channel. This PR creates a separate immutable id for our mappings.
> Split data channel's webrtc id from our internal id

- common/darwin/Classes/FlutterRTCPeerConnection.m
Previously it was possible that the data channel on the dart side would be created before event channel was ready. This moves event sink lower and is triggered in main thread.
> Fixes DataChannel issue described in #974

- common/cpp/include/flutter_webrtc_base.h
If the EncodableValue is int32_t, findLongInt will throw a std::bad_variant_access exception.
Please refer to https://github.com/flutter-webrtc/flutter-webrtc/issues/989
> Fix variant exception of findLongInt.

- common/darwin/Classes/FlutterRTCDataChannel.h
- common/darwin/Classes/FlutterRTCDesktopCapturer.m
- common/darwin/Classes/FlutterRTCMediaStream.m
- common/darwin/Classes/FlutterWebRTCPlugin.h
- common/darwin/Classes/FlutterWebRTCPlugin.m
Fix compilation warnings under iOS/macOS
```
2022-07-18 11:01:26.250 xcodebuild[8395:113863] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-18 11:01:26.251 xcodebuild[8395:113863] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:9B436656-E6E8-5C29-BA5E-C573E7003F09 }
{ platform:macOS, name:Any Mac } …
```
> fix: Fix compile warning for Darwin.

- common/darwin/Classes/FlutterRTCMediaStream.m
I was facing issues with iOS. I can not change the camera resolutions in the iOS version.
Didn't see these issues with Android.
It was caused by a mismatched data type in the media constraints (Dart <-> Object C)
- if we set the media constraints like that, **it will not work.**
```
final Map<String, dynamic> mediaConstraints = {
'audio': true,
'video': {
'width: 640, 
'height': 480,
'frameRate': 24,
'facingMode': 'user',
'optional': [],
}
};
```
- if we set the media constraints like that, **it will work.**
```
final Map<String, dynamic> mediaConstraints = {
'audio': true,
'video': {
'width: '640', 
'height': '480',
'frameRate': '24',
'facingMode': 'user',
'optional': [],
}
};
```
- Because width, height, and framerate are converted to NSString on Object C.
- The logic is set from …
> fix : iOS app could not change camera resolutions 

- common/darwin/Classes/FlutterRTCMediaStream.m
It's related to my recent PR https://github.com/flutter-webrtc/flutter-webrtc/pull/1033
The source code could not compile after the PR https://github.com/flutter-webrtc/flutter-webrtc/pull/1033
[ERROR HERE](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/common/darwin/Classes/FlutterRTCMediaStream.m#L306)
This PR will fix this syntax error so it will not break the codebase anymore. 
`flutter-webrtc` seems to need to be integrated CI pipeline to check the PR before merging it  
@cloudwebrtc
> hotfix : iOS : Missing '[' at start of message send expression

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
Fix get render null because renders is map, should use valueAt for avoiding null when get item
Explain:
when RTCVideoRenderer initialize, entry.id() is increase 1
if i create 4 RTCVideoRenderer and call initialize, i have 0 1 2 3
I delete 3 4, i have 0 1
I recreate 2 RTCVideoRenderer, i will have 0 1 4 5
So when use renders.get(i) with i = 2 or 3, renderer is null
> Update MethodCallHandlerImpl.java - Fix renderer null object

- lib/src/native/rtc_video_renderer_impl.dart
This PR will provide a callback to notify user that the first frame is rendered.
User can use it to know when first frame of a stream is started playing.
> Added callback onFirstFrameRendered

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
Premise: When the app is swiped off on android, `dispose` functions are not called in flutter as the engine is being disposed. Thus the streams, tracks, as well as the peer connections leak and await being deallocated by the system upon memory purging of the process. Until that happens the mic and phone activity indicators on modern android versions show that they are being used by the "supposedly" closed app. 
This PR closes and disposes of the local streams, tracks, connections when the engine is detached instead of just clearing the lists. As this already leaks the undisposed connections.
> Dispose streams and connections

- common/cpp/include/flutter_video_renderer.h
- common/cpp/include/flutter_webrtc_base.h
- common/cpp/src/flutter_video_renderer.cc
- common/cpp/src/flutter_webrtc.cc
- common/cpp/src/flutter_webrtc_base.cc
In multiple peerconnection find stream id by for loop. But stream id for each peerconnection may be the same.
> Have same remote streams id then found wrong MediaStream.

- common/darwin/Classes/FlutterRTCMediaStream.m
For IOS, the navigator.mediaDevices.enumerateDevices() method returns an empty one to groupId. This fixed the problem.
> Fix groupId #1145 for IOS 

- common/darwin/Classes/AudioUtils.m
First of all, sorry for my terrible English
**[Environment]**
iOS 16+
flutter-webrtc: 0.9.11
**[Device]**
iphone xs, iphone12
**[Issue]**
After calling setSpeakerphoneOn, when switching Bluetooth earphones and speakers, the sound session is not changed and the result of calling the method is maintained.
**[Reproduction procedure]**
- successful webrtc connection.
- Check earphone connection status through AVAudioSession outputs.
- Call setSpearkerphoneOn according to the connection status.
- Bluetooth earphone connection.
- AVAudioSessionRouteChangeNotification observer not working.
- Only the speaker is output.
**[Resolution]**
- Add overrideOutputAudioPort method.
- Change withOptions to enable continuous sound session route change detection.
- Moved setMode forward because of the …
> fix: :bug: Fixed the problem that iOS earphones and speakers do not switch

- common/darwin/Classes/FlutterWebRTCPlugin.m
- I was facing issues with iOS. 
- One of the device in the meeting room is a viewer only, it is not has a camera or microphone. It means the candidate has no media source yet. This device joined the meeting and makes all iOS devices crash and out from the meeting. The android devices are not affected. 
> refs:  https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/sdpMLineIndex
> from the document specification ... `sdpMLineIndex` could be `null`.
- But in the iOS code, we are expected `sdpMLineIndex` will be NSString or NSNumber. So that we could call intValue() method to get the value. But actually, in that case, `sdpMLineIndex` is an `NSNull`. And the code crash.
```
Fatal Exception: NSInvalidArgumentException
-[NSNull intValue]: unrecognized selector sent to instance …
```
> fix : iOS crash when `sdpMLineIndex` is null on `addCandidate`

- common/cpp/src/flutter_peerconnection.cc
- common/cpp/src/flutter_screen_capture.cc
For some reason, clang fails to recognize that EncodableList and EncodableMap as acceptable variant types for EncodableValue
> fix compile for linux

- lib/src/native/rtc_peerconnection_impl.dart
iOS throws 
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(AddIceCandidateFailed, Error The remote description was null, null, null) sometimes.
and this change will help to handle it.
> Handle Platform Exception on addCandidate

- android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java
The audio switch is nullified when stopping which disallows further use after a single stop.
Keeping the reference doesn't cause any memory leaks as the encapsulated fields are removed on stop.
> Keep the audio switch after stopping

- lib/src/native/rtc_video_renderer_impl.dart
- lib/src/native/rtc_video_view_impl.dart
- lib/src/web/rtc_video_view_impl.dart
This tiny enhancement of `RTCVideoView` allows simplifying add meaningful placeholder widget while `RTCVideoRenderer` is preparing/initialing.
Also, I am going to use it within integration tests that automate app screenshots creation.
> Enhance RTC video view with placeholder builder property

- common/darwin/Classes/FlutterWebRTCPlugin.m
Pretty significant typo which breaks GcmCryptoSuites.
> fix (easy!): typo which broke GcmCryptoSuites

- common/cpp/src/flutter_media_stream.cc
When PlayoutDeviceName or RecordingDeviceName is used on linux, default device name can exceed default buffer size 128 Bytes. In this case WebRTC returns no null terminated buffer. And building string as
std::string(strNamUTF8) leads to usage of memory outside of buffer.
This unitialized memory can't then be decoded bu flutter code.
> Buffer overflow, while requesting device name

- android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java
The crash only happens on some Android devices (reproduced on Google Pixel 4).
> Fix crash when calling captureFrame on a video track on android (#1129)

- common/darwin/Classes/AudioUtils.m
- 问题：
原来的方法在createStream成功后，但未接通通话前异常断开，或者本身业务设计有接听界面，此时用户断开连接，会导致下次通话无法正常播放声音。
- 修复：
使用RTCAudioSession关闭声音通道，这样无论何种情况下，下次通话声音都正常播放。
> iOS Audio bug fix

- common/darwin/Classes/AudioUtils.m
Without any setActive for rtc session, libwebrtc manages the session counter by itself.
It can solve the bug that the music player automatically resumes playback
> fix: Without any setActive for rtc session, libwebrtc manages the session counter by itself.

- lib/src/native/desktop_capturer_impl.dart
When the sharing window is opened, the newly added page will be displayed in the window. However, after closing the application to be shared and reopening the sharing window, the application interface still exists
> Fix: After the window is closed, the old source still exists

- common/darwin/Classes/AudioUtils.m
This is a PR to fix for Issue #1284.
Choosing a `AVAudioSessionModeVideoChat` as mode while using `PlayAndRecord` solves the issue of audio being switched to earpiece once the mic is toggled on and vice-versa.
> BugFix: iOS audio ouptut switching when toggling mic

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- common/darwin/Classes/FlutterWebRTCPlugin.m
- lib/src/helper.dart
- lib/src/native/media_recorder_impl.dart
- lib/src/native/media_stream_impl.dart
- lib/src/native/media_stream_track_impl.dart
- lib/src/native/rtc_peerconnection_impl.dart
- lib/src/native/rtc_rtp_receiver_impl.dart
- lib/src/native/rtc_rtp_sender_impl.dart
All operations on track objects in the flutter API just send the track id to the platform specific code without the additional information which peer connection the track belongs to. This leads to methods like captureFrame() being called on the wrong track if there are tracks with the same id in more than one peer connection.
Fixes #469
> Fix track lookup in the platform specific code for Android and iOS

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java
- common/cpp/include/flutter_peerconnection.h
- common/cpp/src/flutter_peerconnection.cc
- common/cpp/src/flutter_webrtc.cc
- common/darwin/Classes/FlutterWebRTCPlugin.m
- lib/src/native/rtc_rtp_sender_impl.dart
- pubspec.yaml
In order to have transceiver-only usage in RTC sessions, RTCRtpSender must be able to have streams set as per https://blog.mozilla.org/webrtc/rtcrtptransceiver-explored/
This PR enriches the Flutter API `RTCRtpSender` with the method `addStreams`
Depends on https://github.com/flutter-webrtc/webrtc-interface/pull/15 & https://github.com/flutter-webrtc/dart-webrtc/pull/23 -> these need to be merged before merging this one
> Add  `addStreams` to `RTCRtpSender`

- common/cpp/src/flutter_peerconnection.cc
- common/cpp/src/flutter_webrtc.cc
If `RTPTransceiver` is null, GetCurrentDirection crashes on Windows
> [Windows/Linux] Fix uneffective RTPTransceiver::GetCurrentDirection

- common/cpp/src/flutter_peerconnection.cc
libwebrtc implementation wasn't calling `RTCRtpTransceiver::current_direction`
> [Windows/Linux] `RTPtransceiver::getCurrentDirection` returns correct value

- lib/src/helper.dart
`setMicrophoneMute()` is async but didn't return a Future, which makes it not usable with `await`.
> Fix setMicrophoneMute() not awaitable

- common/cpp/include/flutter_frame_capturer.h
- common/cpp/src/flutter_frame_capturer.cc
- common/cpp/src/flutter_peerconnection.cc
- example/lib/main.dart
- example/lib/src/capture_frame_sample.dart
- linux/CMakeLists.txt
- third_party/svpng/LICENSE
- third_party/svpng/svpng.hpp
- windows/CMakeLists.txt
add linux desktop support to capture a single frame from `MediaStreamTrack`
- The `FlutterFrameCapturer` class registers as `RTCVideoRenderer` and saves the next frame as file into `/tmp/captureFrame.png`. After success the flutter implementation reads the file and returns its content.
- The file will be saved as PNG through ~~lodepng~~ svpng
Tested on Ubuntu 22.04 aarch64 
See also #838
> Add implementation to MediaStreamTrack.captureFrame() for linux

- linux/CMakeLists.txt
Adds $ORIGIN to the RPATH of the plugin, to be able to find the libwebrtc.so file after distributing the bundle. 
will solve: 
#1212
#1241
> fix: libwebrtc.so: no such file or directory 

- lib/src/native/rtc_video_view_impl.dart
When the `srcObject` value changes (and as a consequence, the `renderVideo` value of `videoRenderer` changes) in a place not related to the widget without a `setState` call (for example within a bloc), the associated `RTCVideoView` widget does not rebuild. As a result, it continues to display a placeholder or Container widget, even if `RTCVideoRenderer.renderVideo` is `true`.
In this pull request, I expand the usage of the `ValueListenableBuilder` widget, which already exists within `RTCVideoView` widget. This allows the actual `renderVideo` value to be respected and triggers a partial rebuild of the `RTCVideoView` widget when the value changes.
By the way in `RTCVideoView` for web this done by [`_onRendererListener`](https://github.com/flutter-webrtc/flutter-webrtc/blob/fad3b5720309651618 …
> Partially rebuild RTCVideoView when renderVideo value changes

- android/build.gradle
Original issue: https://github.com/livekit/client-sdk-android/issues/251
> fix: fix android earpiece not being replaced after wired headset is disconnected

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/audio/AudioSwitchManager.java
- lib/src/helper.dart
- lib/src/native/android/audio_configuration.dart
- Expose helper method to clearCommunicationDevice
- Add case: AndroidAudioFocusMode.loss 
Android documentation recommends that when an app finishes a call or session, we should clear the active communication device: https://developer.android.com/guide/topics/connectivity/ble-audio/audio-manager#end_the_session
In addition, we should tell the Audio Manager that we want to gain and lose the audio focus:
https://developer.android.com/reference/kotlin/androidx/media/AudioManagerCompat#AUDIOFOCUS_GAIN()
This fix will help to ensure that the user can return to their original audio stream when a webrtc session is finished. 
May resolve https://github.com/flutter-webrtc/flutter-webrtc/issues/351
> Fix: [Android] Expose helper to clearCommunicationDevice on AudioManager.AUDIOFOCUS_LOSS

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- common/darwin/Classes/FlutterRTCMediaStream.h
- common/darwin/Classes/FlutterRTCMediaStream.m
- common/darwin/Classes/FlutterWebRTCPlugin.m
- example/lib/src/get_user_media_sample.dart
- lib/src/helper.dart
- lib/src/native/media_stream_track_impl.dart
iOS and AOS support (tested on iOS and AOS mobile devices)
How to use?
final videoTrack = _localStream!
.getVideoTracks()
.firstWhere((track) => track.kind == 'video');
await WebRTC.invokeMethod('mediaStreamTrackSetZoom',
<String, dynamic>{'trackId': videoTrack.id, 'zoomLevel': zoomLevel});
//After [this PR](https://github.com/flutter-webrtc/webrtc-interface/pull/20) is published. 
(webrtc_interface version needs to be updated  in pubspec.yaml)
await videoTrack.setZoom(zoomLevel);
> Added setZoom method to support camera zooming while streaming.

- common/cpp/include/flutter_frame_capturer.h
- common/cpp/src/flutter_frame_capturer.cc
When i use flutter-webrtc plugin build my app on window 10, i got this error like belowing
"D:\a_work\1\s\src\vctools\crt\github\stl\src\mutex.cpp(164): unlock of unowned mutex".
so i had to read some relative source code, i found some problems in flutter_frame_capturer.cc file, i fix them and it work
> fix "unlock of unowned mutex" error when call "captureFrame()" func on windows

- lib/src/web/rtc_video_renderer_impl.dart
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
> Fix: platformViewRegistry getter is deprecated

- analysis_options.yaml
- common/cpp/src/flutter_webrtc.cc
- example/analysis_options.yaml
* libwebrtc should been updated, the crash issue has been fixed because of invalid candidate or session description.
* Empty candidate means all candidates have been received, it's a valid value.
* Add null check for candidate or session description.
> Check the invalid value of candidate and session description.

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
When you use the android screen capture feature, it provides an incorrect capture size; in most cases, this bug may not be a significant issue. However, it becomes problematic when working with the Flutter overlay view. (iOS works okay.)
The log is shown below.
2023-12-27 14:56:27.549 14766-14766 FlutterWebRTCPlugin D OrientationAwareScreenCapturer.startCapture: 1080x2122@30
Test Device: Galaxy S20 Ultra 5G
Device screen size: 1080x2316
> fix android wrong screen capture size.

- example/android/app/src/main/AndroidManifest.xml
New permission is required for screen share in Android 14:
https://developer.android.com/about/versions/14/changes/fgs-types-required
> Add foreground media projection perm to example app for Android 14

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
- android/src/main/java/com/cloudwebrtc/webrtc/OrientationAwareScreenCapturer.java
- lib/src/helper.dart
After AOS 14, changeCaptureFormat() should resize the VirtualDisplay instead of recreating it due to the limitation on reusing MediaProjectionPermissionResultData. And it is necessary to obtain capture permission first and request foreground service; otherwise, the app crashes due to the media projection permission policy.
Use Helper.requestCapturePermission() to obtain capture permission on Android 14 specially targetSdkVersion 34 or above.
Tested on Android 13, 14 and targetSdkVersion 33, 34 combinations.
> support media projection feature for android 14

- common/cpp/include/flutter_frame_cryptor.h
- common/cpp/src/flutter_frame_cryptor.cc
- common/cpp/src/flutter_webrtc.cc
Fixes #1504 
Fixes #1525
This fixes an issue in the handling of unimplemented methods. 
Because all unimplemented methods result in a call to `HandleFrameCryptorMethodCall`, which contains a `move` on the `result` pointer, if we later try to call `result.NotImplemented` it fails because `result` pointer was nullified during this move https://github.com/flutter-webrtc/flutter-webrtc/blob/81d3d845183c7e2884800477bc01414cc5778774/common/cpp/src/flutter_webrtc.cc#L1244
This fixes the issue by moving `result` back out of the function call in the case of `HandleFrameCryptorMethodCall` fails. Not sure how we feel about using out parameters like this, but this felt like the simplest fix to me. Open to suggestions for alternatives!
> Fix handling of unimplemented method

- common/darwin/Classes/FlutterWebRTCPlugin.m
otherwise event like "onTrackAdd" will call setSpeakerphoneOn even though I called setSpeakerphoneOnButPeferBluetooth before.
> fix(iOS): remember speakerphone mode for ensureAudioSession

- android/src/main/java/com/cloudwebrtc/webrtc/audio/AudioSwitchManager.java
Without this call, `enableSpeakerButPreferBluetooth` doesn't do anything if it finds a headset
> fix(Android): actually call selectAudioOutput in enableSpeakerButPreferBluetooth

- ios/Classes/FlutterRTCVideoPlatformView.m
- lib/src/native/rtc_video_platform_view.dart
I tried `RTCVideoPlatFormView` and realized that objectFit is `cover` doesn't seem to work properly, `contain` does as expected. 
After fix:
| Cover | Contain |
|-------|-------|
| <img src="https://github.com/flutter-webrtc/flutter-webrtc/assets/60530946/93f06b0c-44b0-4b2f-a660-452fc9c611ce" width="250px"/> | <img src="https://github.com/flutter-webrtc/flutter-webrtc/assets/60530946/b5995f90-9336-4a53-83f2-782218f22f09" width="250px"/> |
> fix: fit cover works wrong

- android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
Check if RtpSender and its MediaStreamTrack from PeerConnection are not null when looking for a MediaStreamTrack of kind audio when finding a RtpSender to call insertDtmf in onMethodCall case: 'sendDTMF'.
> Fixes #1611, Resolve running into a NullPointerException on finding RtpSender for sendDTMF

- example/lib/src/loopback_data_channel_sample.dart
**STATUS**: Ready for review
---
The current example does:
```dart
@override
void initState() {
super.initState();
}
```
The above is redundant since there is no logic within the overridden `initState`.
> refactor: remove redundant init method in "loopback data channel" example

- example/lib/src/loopback_data_channel_sample.dart
**STATUS**: Ready for review
---
The current example uses an `OrientationBuilder`, the builder provides an `orientation`, since this `orientation` value is unused the widget is useless.
Removing the widget clears the widget tree, making it more readable and simplifies the example for new readers.
> refactor: remove unused OrientationBuilder in "loopback data channel" example

- example/lib/src/loopback_data_channel_sample.dart
**STATUS**: Ready for review
---
The current example uses abbreviated members "pc" and "dc". This Pull Request renames the terms to their full name.
According to the [Effective Dart](https://dart.dev/effective-dart/documentation#avoid-abbreviations-and-acronyms-unless-they-are-obvious):
> AVOID abbreviations and acronyms unless they are obvious
Many people don't know what "i.e.", "e.g." and "et al." mean. That acronym that you're sure everyone in your field knows may not be as widely known as you think.
These abbreviated terms (_pc_ and _dc_) should be avoided, at least in an example. An example is a piece of code that newcomers (yet to be familiar with the library) use when trying to learn how the library operates and what it can do.
> refactor: rename abbreviated members in "loopback data channel" example

- android/src/main/java/com/cloudwebrtc/webrtc/CameraEventsHandler.java
- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
- lib/src/native/adapter_type.dart
- lib/src/native/android/audio_configuration.dart
- lib/src/native/ios/audio_configuration.dart
- pubspec.yaml
When the camera is opened or closed quickly, `getUserMedia` will be stuck in the camera opening state, so we need to confirm that the camera has been fully opened or closed when `getUserMedia` or `track.stop()`.
> Fixed critical error when opening/closing camera.

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
- android/src/main/java/org/webrtc/Camera1Helper.java
- android/src/main/java/org/webrtc/Camera2Helper.java
- common/darwin/Classes/FlutterRTCMediaStream.m
MediaStreamTrack settings should report the actual values rather than the target values given by constraints. 
Also remove adaptOutputFormat due it causing extreme downscaling.
Addresses https://github.com/webrtc-sdk/webrtc/issues/133
> Report actual sizes for camera media stream track and remove adaptOutputFormat usage

- common/darwin/Classes/FlutterWebRTCPlugin.h
- common/darwin/Classes/FlutterWebRTCPlugin.m
This PR introduces a shared singleton instance for the `FlutterWebRTCPlugin`, allowing it to be accessed externally. This modification is crucial for the implementation of Picture-in-Picture (PiP) mode on iOS using WebRTC video tracks.
> added shared singleton for FlutterWebRTCPlugin

- common/darwin/Classes/FlutterRTCDesktopCapturer.m
When using the broadcast capturer on iOS, the `deviceId` constraint can now be set to `broadcast-manual` instead of `broadcast` to allow capture to begin without presenting the broadcast picker. When using this option, the user is responsible for managing the broadcast state externally. 
This change is non-breaking.
> feat: Add option to start capture without broadcast picker

- lib/src/web/rtc_video_renderer_impl.dart
sometimes video callbacks (onResize, onCanPlay) come before element is findable in DOM. This PR adds
the created element as fallback
fixes #1804
> fix: race condition in RTCVideoRenderer for Web

- android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
Calling `setPreferredInputDevice` will cause HW AEC/NS failure on some devices, causing echo during voice calls. Known devices include Galaxy S25 Ultra, Galaxy Z Fold6.
In addition, we should avoid using [Helper.selectAudioInput](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/helper.dart#L108) during a call to avoid causing echo cancellation failure on these devices.
> [Android] fix: remove setPreferredInputDevice when getUserAduio.

- android/src/main/java/com/cloudwebrtc/webrtc/record/VideoFileRenderer.java
The current stop function does not wait for the recording process to fully stop before proceeding. This can lead to corrupted files, as the audio or video thread may still be accessing the file when the app attempts to move it to the user's Movies directory. This MR updates the stop function to ensure it waits for the recording to completely stop, preventing file corruption.
> Resolve android corrupted recordings

- android/src/main/java/com/cloudwebrtc/webrtc/video/camera/CameraUtils.java
I don't have a better solution at the moment, but `handleOrientationChange` looks empty so this should be ok.
Fixes: https://github.com/flutter-webrtc/flutter-webrtc/issues/1744, https://github.com/flutter-webrtc/flutter-webrtc/issues/1799
> fix: calls in terminated mode by disabling orientation manager

- android/src/main/java/com/cloudwebrtc/webrtc/record/VideoFileRenderer.java
Previously, the code started the muxer as soon as either the audio or video track was added, which could cause the app to crash. The updated logic ensures that the muxer only starts after both the audio and video tracks have been added.
> Ensure both video and audio tracks are added before starting the muxer

- CHANGELOG.md
- ios/flutter_webrtc.podspec
- macos/flutter_webrtc.podspec
- pubspec.yaml
[1.0.0] - 2025-07-25
* Bump version to 1.0.0
* [Native] feat: Upgrade libwebrtc to m137. (#1877).
* [Doc] Fix: typo in package description (#1895)
* [Android] fix: Video recording crashing and freezing on Android 14 Devices (#1886)
* [Android] fix: Add audio recording for Android Platform (#1884)
* [Dart] fix: Removed outdated code to avoid UI not being displayed in Windows release mode (#1890)
* [Apple] fix: Fix compile warnings (#1887)
* [Apple] feat: Update to m137 with audio engine (#1875)
* [Android] fix: Ensure both video and audio tracks are added before starting the muxer (#1879)
> release: 1.0.0.

- android/proguard-rules.pro
to fix 
`java.lang.ClassNotFoundException: org.jni_zero.JniInit`
error in android release builds for version 1.0.0 (flutter_webrtc: ^1.0.0)
> fix: java.lang.ClassNotFoundException: org.jni_zero.JniInit

- lib/src/web/rtc_video_renderer_impl.dart
- lib/src/web/rtc_video_view_impl.dart
Resurfaces @jezell's texture-based video rendering from #1670. Fixes camera rendering failures in large meetings, reduces DOM overhead, enables native Flutter compositing, and adds shader/effect support for video.
- **New default**: Video frames captured from hidden HTML elements and painted via CustomPaint
- **Performance**: Solves rendering failures in large meetings (livekit/client-sdk-flutter#465)
- **Effects support**: Cameras work with Flutter renderer for shaders/blurs
- **Fallback**: Original behavior via `WEBRTC_USE_HTML_ELEMENT_VIEW=true`
- Frame capturing using `createImageFromTextureSource()`
- `requestVideoFrameCallback` with `requestAnimationFrame` fallback
- Smart caching - only captures when video time changes
- Custom painter for mirroring support
Original work by @jezell …
> Add texture-based video rendering for web (resurface #1670)

- lib/src/native/rtc_video_platform_view_controller.dart
- lib/src/native/rtc_video_renderer_impl.dart
- lib/src/video_renderer_extension.dart
- lib/src/web/rtc_video_renderer_impl.dart
Paired with https://github.com/flutter-webrtc/webrtc-interface/pull/33
Tested on web with chrome, never tested other platforms but since already presented Helper class do it can't see any problems with that. I thought it's actually may be of use, can't imagine production ready app without this functionality present clear where you expect it to find.
> small setVolume addition
