flutter-webrtc/flutter-webrtc

lib/rtc_video_view.dart
=> Add public getter for texture id

.gitignore, android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterRTCMediaStream.m, ios/Classes/FlutterWebRTCPlugin.m, lib/media_stream_track.dart
=> #39: Implemented MediaStreamTrack.setVolume()

android/build.gradle, android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/record/AudioSamplesInterceptor.java, android/src/main/java/com/cloudwebrtc/webrtc/record/MediaRecorderImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/record/VideoFileRenderer.java, example/android/app/build.gradle, example/android/app/src/main/AndroidManifest.xml, example/lib/src/get_user_media_sample.dart, example/pubspec.yaml, lib/media_recorder.dart, lib/webrtc.dart
Tested on 9.0, 8.0 and 5.0
Stable enough for merge
When providing audio track, only local audio track is recorded
Filled an issue to webrtc: https://bugs.chromium.org/p/webrtc/issues/detail?id=10166
=> Media recorder implementation on android

android/src/main/java/com/cloudwebrtc/webrtc/DataChannelObserver.java, android/src/main/java/com/cloudwebrtc/webrtc/FlutterRTCVideoRenderer.java, android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, android/src/main/java/com/cloudwebrtc/webrtc/utils/AnyThreadResult.java, android/src/main/java/com/cloudwebrtc/webrtc/utils/AnyThreadSink.java
=> Patches for #87

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterWebRTCPlugin.m
Used in our app where the caller can capture frame from the receiver's stream.
=> Make startRecordToFile and captureFrame able to capture remote tracks

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterWebRTCPlugin.m, lib/media_stream_track.dart
Adds support for microphone mute feature in Android/iOS.
=> Microphone mute

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterWebRTCPlugin.m, lib/media_stream_track.dart
Adds support for speakerphone feature in Android/iOS.
=> Speakerphone

android/build.gradle, android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, ios/Classes/FlutterWebRTCPlugin.m
ref : https://github.com/cloudwebrtc/flutter-webrtc/issues/106
=> fix(Peer-connections) split dispose and close methode 

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java
I fixed an issue when IceServerMap has an array of url strings and also username and credentials.
=> [Android] Fix 'createIceServer' method Invalid value error

ios/Classes/FlutterRTCMediaStream.h, ios/Classes/FlutterRTCMediaStream.m, ios/Classes/FlutterWebRTCPlugin.m, lib/media_stream_track.dart
This currently only implements the iOS side of this. There seems like there could be a way to get this to work on Android, but it's a bit hacky since it involves keeping a modified copy of the `CameraSession` class from the upstream WebRTC project here. If this is something you would interested in I'd be happy to look into it, but we would be happy just to have this on iOS ☺️ 
ref: https://stackoverflow.com/a/56656932/148072
=> Add method for setting torch state

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java, example/lib/src/get_user_media_sample.dart
I have tested this on a BlackView A10 (which uses the Camera1 API) and @MrAlek have tested this on a Samsung Galaxy A40 (which uses the Camera2 API)
=> Android torch support

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterRTCVideoRenderer.h, ios/Classes/FlutterRTCVideoRenderer.m, ios/Classes/FlutterWebRTCPlugin.h, ios/Classes/FlutterWebRTCPlugin.m, lib/get_user_media.dart, lib/media_stream.dart, lib/rtc_peerconnection.dart, lib/rtc_video_view.dart, macos/Classes/FlutterRTCVideoRenderer.h, macos/Classes/FlutterRTCVideoRenderer.m, macos/Classes/FlutterWebRTCPlugin.h, macos/Classes/FlutterWebRTCPlugin.m
Fixed rendering issues caused by remote MediaStream using the same msid/label when using multiple PeerConntions.
=> Fix render issue

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterRTCVideoRenderer.h, ios/Classes/FlutterRTCVideoRenderer.m, ios/Classes/FlutterWebRTCPlugin.h, ios/Classes/FlutterWebRTCPlugin.m, lib/get_user_media.dart, lib/media_stream.dart, lib/rtc_peerconnection.dart, lib/rtc_video_view.dart
=> 修复Flutter-WebRTC多人视频时的bug

android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java
Opening this for early feedback. The `rotate*` functions are horribly broken right now because I don't know anything about YUV 😄 
I'll probably get time to complete this next week, but I'm away on other things for the few coming days now. Just wanted to open it in case someone else is also working on this.
links:
- https://developer.android.com/reference/android/graphics/YuvImage
- https://stackoverflow.com/questions/15131663/how-to-change-orientation-of-captured-byte-frames-through-onpreviewframe-callb
- https://stackoverflow.com/questions/14167976/rotate-an-yuv-byte-array-on-android
- https://stackoverflow.com/questions/23107057/rotate-yuv420-nv21-image-in-android
- http://www.wordsaretoys.com/2013/10/25/roll-that-camera-zombie-rotation-and-coversion-from-yv12-to-yuv420planar/
- …
=> Fix Android frame orientation

example/ios/Podfile
related to https://github.com/cloudwebrtc/flutter-webrtc/pull/172
=> fix(ios): update ios platform to 10.0

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java
=> [Android] Removed duplicate method that was causing compilation error

android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, ios/Classes/FlutterWebRTCPlugin.m, ios/flutter_webrtc.podspec, lib/media_stream_track.dart, lib/rtc_rtp_receiver.dart, lib/rtc_rtp_sender.dart
I have enabled the new addTrack API for ios and android as well as added a few runtime checks for robustness
=> enabled addTrack API for android and ios

ios/Classes/FlutterRTCMediaStream.m
for more details see the conversation - https://github.com/cloudwebrtc/flutter-webrtc/pull/228
=> [iOS] stop capture RTCVideoSource if it been opened before

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
add videoConstraintsMandatory is null judgment
=> Fix Android crash when getUserVideo

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, ios/Classes/FlutterRTCMediaStream.h, ios/Classes/FlutterRTCMediaStream.m, ios/Classes/FlutterWebRTCPlugin.m, lib/rtc_peerconnection_factory.dart, lib/web/rtc_peerconnection_factory.dart, lib/web/rtc_video_view.dart
This PR implements the feature request in Issue #253
=> Adding createLocalMediaStream method to PeerConnectionFactory

android/src/main/java/com/cloudwebrtc/webrtc/DataChannelObserver.java, ios/Classes/FlutterRTCDataChannel.m, ios/Classes/FlutterRTCPeerConnection.m, lib/rtc_data_channel.dart, macos/Classes/FlutterRTCDataChannel.m, macos/Classes/FlutterRTCPeerConnection.m
=> Add peerConnectionId to data channel EventChannel

lib/web/rtc_video_view.dart
add key parameters
Keep consistent with other platform versions
=> add key parameters

.gitignore, lib/web/rtc_video_view.dart
ADD - Just add a reference to a stackoverflow answer for discussion if needed for the view
=> FIX - #295

lib/media_stream.dart
REFACTOR - Avoid code duplication
FIX - call methodChannel twice
REFACTOR - Remove unnecessary new keyword
=> MediaStream - Code cleanup

lib/rtc_peerconnection.dart, lib/web/rtc_peerconnection.dart
FIX - missing null check onIceGatheringState (web)
REFACTOR - add final keyword
REFACTOR - remove new keyword
REFACTOR - replace if statement by null check operator for readability
FIX - Adding stream twice to the _remoteStream list
=> Fix - NPE if onIceGatheringState is not defined

analysis_options.yaml, example/lib/src/get_user_media_sample_web.dart, lib/enums.dart, lib/get_user_media.dart, lib/media_recorder.dart, lib/media_stream.dart, lib/media_stream_track.dart, lib/rtc_data_channel.dart, lib/rtc_ice_candidate.dart, lib/rtc_peerconnection.dart, lib/rtc_peerconnection_factory.dart, lib/rtc_session_description.dart, lib/rtc_video_view.dart, lib/utils.dart, lib/web/get_user_media.dart, lib/web/media_recorder.dart, lib/web/media_stream.dart, lib/web/media_stream_track.dart, lib/web/rtc_data_channel.dart, lib/web/rtc_ice_candidate.dart, lib/web/rtc_peerconnection.dart, lib/web/rtc_peerconnection_factory.dart, lib/web/rtc_session_description.dart, lib/web/rtc_video_view.dart, pubspec.yaml
I changed code a little bit the code logic in : lib/media_stream.dart
please comment if you have any concerns
I added a pedandic to dev_dependency to make our code "compliant"
=> Apply pedantic warning - to improve score point on pub.dev

.gitignore, lib/src/media_stream.dart, lib/src/rtc_ice_candidate.dart, lib/src/rtc_video_view.dart, lib/src/web/media_recorder.dart
continue cleaning
remove duplicate call to notifyListeners() -> already call in the setter
fix potential concurrency issue
=> cleaning and fix potential concurrency issue

lib/src/rtc_video_view.dart, lib/src/web/rtc_video_view.dart
Web: Reuse code to prevent copy and paste code
Web: Remove confusing print, move to the API comment
Mobile: Add null check to prevent passing null to native implementations
=> continue cleaning and code robustness

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, example/lib/src/loopback_sample.dart, ios/Classes/FlutterWebRTCPlugin.m, lib/flutter_webrtc.dart, lib/src/rtc_dtmf_sender.dart, lib/src/rtc_peerconnection.dart, lib/src/web/rtc_dtmf_sender.dart, lib/src/web/rtc_peerconnection.dart, macos/Classes/FlutterWebRTCPlugin.m
Added dtmf functions  to IOS and Android,
peerConnectionId getter added to RTCPeerconnection.dart
Fix https://github.com/flutter-webrtc/flutter-webrtc/issues/292
=> dtmf sending added

pubspec.yaml, test/unit/rct_peerconnection_test.dart
An attempt to add a first test to validate that not setting any public delegate will not throw a NPE
=> Let's add a first test

android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, common/darwin/Classes/FlutterRTCPeerConnection.m, common/darwin/Classes/FlutterWebRTCPlugin.h, common/darwin/Classes/FlutterWebRTCPlugin.m, lib/src/native/rtc_peerconnection_impl.dart
=> Add transceiver to onTrack events.

.gitignore, example/lib/src/get_display_media_sample.dart, lib/src/web/media_stream_impl.dart, lib/src/web/media_stream_track_impl.dart
Add onEnded for Web
Add onMuted for Web
Modify example to add comments
=> Support catch of stop sharing for Web

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
The method tried to find the tracks in the localTRacks map instead of parsing peerconnection remote track
=> Fix adding track to stream 

example/lib/src/get_display_media_sample.dart, example/lib/src/get_user_media_sample_web.dart, lib/flutter_webrtc.dart, lib/src/helper.dart, lib/src/interface/media_stream.dart, lib/src/interface/media_stream_track.dart, lib/src/interface/mediadevices.dart, lib/src/interface/navigator.dart, lib/src/native/media_stream_impl.dart, lib/src/native/media_stream_track_impl.dart, lib/src/native/mediadevices_impl.dart, lib/src/web/media_stream_impl.dart, lib/src/web/media_stream_track_impl.dart, lib/src/web/mediadevices_impl.dart, lib/src/web/rtc_rtp_receiver_impl.dart, lib/src/web/rtc_rtp_sender_impl.dart
Add missing property muted in MediaStreamTrack
Add missing callback handler for onUnMuted in MediaStreamTrack
Add missing API for MediaSteam(active and clone)
=> [WIP] - Add API documentation and missing entries for MediaStream, MediaStreamTrack and MediaDevice

lib/src/native/rtc_video_view_impl.dart, lib/src/web/rtc_video_view_impl.dart
Implements [this](https://github.com/flutter-webrtc/flutter-webrtc/issues/445).
Missing web support.
=> Add FilterQuality to RTCVideoView

lib/src/helper.dart
Hi,
This will fix issue #461 (inverted microphone mute state). 
Thanks.
Tested on Android 9 & 10.
=> Fix setMicrophoneMute

README.md
=> Add Stream sponsorship

lib/src/native/rtc_video_view_impl.dart
The box should IMHO not overflow.
=> Clip behaviour

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
1.  Fix bug** #551
- Add variable VideoCapturerInfo->isScreenCapture.
- Do not call reStartCamera in case of screen capture
2. Add options "cryptoOptions" when create peerconnection so user can enable Gcm crypto which is much faster.
=> Do not call reStartCamera() for screen capture

lib/src/native/media_stream_impl.dart
[issue](https://github.com/flutter-webrtc/flutter-webrtc/issues/594)
=> fix: null check

README.md
This PR updates the URL used in by the Stream banner in the project's README.
=> Update Stream sponsorship URL

lib/src/web/rtc_data_channel_impl.dart
=> Fix sending binary data over DataChannel in web implementation.

common/darwin/Classes/FlutterWebRTCPlugin.m
the problem was with webrtc forcing the AVAudioSessionCategoryPlayAndRecord which overrides the microphone to use the built-in
added force replacement of the category with AVAudioSessionCategoryPlayAndRecord, so that the external microphone can be detected
=> add support for lightning microphone

example/lib/src/loopback_sample.dart
Fix error reported at https://github.com/flutter-webrtc/flutter-webrtc/issues/572
=> set setup attribute to active at SDP answer for loopback example

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
=> fix: correct misspell in method screenRequestPermissions

android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt
This fixes Android hardware encoding for H264.
See https://github.com/livekit/client-sdk-android/pull/67 for other discussion.
=> Fix simulcast factory not sending back EncoderInfo

README.md, android/build.gradle, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/utils/RTCBluetoothManager.java
=> Android 12 bluetooth permissions

lib/src/native/rtc_data_channel_impl.dart, test/unit/rtc_peerconnection_test.dart
=> fix: fix wrong id type for data-channel.

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, common/darwin/Classes/FlutterWebRTCPlugin.m, example/lib/main.dart, example/lib/src/loopback_sample_unified_tracks.dart, lib/src/native/rtc_rtp_sender_impl.dart
I've added an example page as well showing starting and stopping the local cam and mic before the remote connection is established.
Relies upon a PR #4 in webrtc-interface
https://github.com/flutter-webrtc/webrtc-interface/pull/4
=> Support null tracks in sender replace track and set track

CHANGELOG.md, android/src/main/java/com/cloudwebrtc/webrtc/DataChannelObserver.java, lib/src/native/rtc_data_channel_impl.dart, pubspec.yaml
Immplemented for android:
created pull request for webrtc_interface 1.0.5
onBufferedAmountChange
bufferedAmount
onBufferedAmountLow
bufferedAmountLowThreshold
=> Implemented features for android

common/darwin/Classes/FlutterRTCMediaStream.m
=> Fix issue 1000

android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, common/cpp/src/flutter_peerconnection.cc, common/darwin/Classes/FlutterWebRTCPlugin.m, lib/src/native/rtc_peerconnection_impl.dart, test/unit/rtc_peerconnection_test.dart
=> fix typo peerConnectoinEvent -> peerConnectionEvent

android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, common/cpp/src/flutter_peerconnection.cc, common/darwin/Classes/FlutterWebRTCPlugin.m, lib/src/native/rtc_peerconnection_impl.dart, test/unit/rtc_peerconnection_test.dart
Addresses #1017 on main branch
=> fix typo peerConnectoinEvent -> peerConnectionEvent for EventChannel name

common/cpp/include/flutter_screen_capture.h, common/cpp/include/flutter_webrtc_base.h, common/cpp/src/flutter_screen_capture.cc, common/cpp/src/flutter_video_renderer.cc, common/cpp/src/flutter_webrtc.cc, common/cpp/src/flutter_webrtc_base.cc, common/darwin/Classes/FlutterRTCDesktopCapturer.h, common/darwin/Classes/FlutterRTCDesktopCapturer.m, common/darwin/Classes/FlutterWebRTCPlugin.h, common/darwin/Classes/FlutterWebRTCPlugin.m, example/lib/src/get_display_media_sample.dart, example/lib/src/widgets/screen_select_dialog.dart, lib/src/desktop_capturer.dart, lib/src/native/desktop_capturer_impl.dart, lib/src/native/utils.dart, lib/src/web/factory_impl.dart, lib/src/web/utils.dart, macos/flutter_webrtc.podspec, third_party/libwebrtc/include/rtc_desktop_capturer.h, third_party/libwebrtc/include/rtc_desktop_device.h, third_party/libwebrtc/include/rtc_desktop_media_list.h, third_party/libwebrtc/include/rtc_peerconnection_factory.h, third_party/libwebrtc/include/rtc_types.h, windows/CMakeLists.txt
Consistent with macOS API calls, detailed testing is required. after this feature is merged, I think it is possible to bump the version to 0.9.0
=> Feat/screen capture event listener for mac/win

README.md, common/darwin/Classes/FlutterWebRTCPlugin.m, ios/flutter_webrtc.podspec, macos/flutter_webrtc.podspec
=> M104 release for darwin

android/build.gradle
=> update to m104 release.

common/cpp/src/flutter_screen_capture.cc, common/darwin/Classes/FlutterRTCDesktopCapturer.m, example/lib/src/widgets/screen_select_dialog.dart, lib/src/desktop_capturer.dart, lib/src/native/desktop_capturer_impl.dart, macos/flutter_webrtc.podspec
Fixes: 
https://github.com/flutter-webrtc/flutter-webrtc/issues/1042
https://github.com/livekit/client-sdk-flutter/issues/14
Changes:
No thumbnails are created when `getSources`, and the acquisition process is placed in the queue of another thread. After the thumbnails are generated, the generated events notify the flutter to update the images.
=> fix: Fix thumbnails causing UI to get stuck and white flickering when thumbnails update.

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
调用方式
return WebRTC.invokeMethod('setPreferredInputDevice', {'deviceId': '1'});
=> Implementation returns a list of audio sources，imp fun setPreferredInputDevice

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
fix bug with track dispose cannot close video
=> fix bug with track dispose cannot close video

common/cpp/include/flutter_webrtc_base.h, common/cpp/src/flutter_webrtc.cc, example/lib/src/loopback_sample.dart, example/lib/src/loopback_sample_unified_tracks.dart
=> feat: support sendDtmf for windows.

common/cpp/src/flutter_peerconnection.cc, common/cpp/src/flutter_webrtc.cc, example/lib/src/loopback_sample.dart, example/lib/src/loopback_sample_unified_tracks.dart, lib/src/native/rtc_peerconnection_impl.dart, third_party/libwebrtc/include/rtc_peerconnection.h
=> Fixed getStats for windows.

android/src/main/java/com/cloudwebrtc/webrtc/FlutterRTCVideoRenderer.java, android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, android/src/main/java/com/cloudwebrtc/webrtc/StateProvider.java
fix https://github.com/livekit/client-sdk-flutter/issues/166
=> fix: Make sure local stream/track dispose correctly.

android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
=> fix: call mode on app start

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
=> chore: remove bluetooth permission check on peerConnectionInit.

common/darwin/Classes/AudioUtils.m
=> Fixes system sound being interrupted upon start up

pubspec.yaml
Benefit from `dart_webrtc` latest fixes
@cloudwebrtc can you please take a look?
Thanks
=> Update dart_webrtc dependendency

common/darwin/Classes/AudioUtils.h, common/darwin/Classes/AudioUtils.m, common/darwin/Classes/FlutterRTCDesktopCapturer.m, common/darwin/Classes/FlutterRTCMediaStream.m, common/darwin/Classes/FlutterRTCPeerConnection.m, common/darwin/Classes/FlutterWebRTCPlugin.h, common/darwin/Classes/FlutterWebRTCPlugin.m
Close issues:
https://github.com/flutter-webrtc/flutter-webrtc/issues/1101
https://github.com/flutter-webrtc/flutter-webrtc/issues/1119
https://github.com/livekit/client-sdk-flutter/issues/181
https://github.com/flutter-webrtc/flutter-webrtc/issues/1098
=> fix audio route/setSpeakerphoneOn issues.

common/darwin/Classes/FlutterRTCPeerConnection.m
Implement RTCPeerConnectionDelegate didRemoveIceCandidates method.
=> Issue 994: Fix unimplemented didRemoveIceCandidates in RTCPeerConnectionDelegate

example/scripts/add-line.py
Make this usable in Python3.
MacOS removed Python2
=> Update to use Py3 print()

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
Can't distinguish from other threads by name, when I debuging. so I want update this thread name.
=> refactor: update thread name

common/darwin/Classes/FlutterRTCFrameCapturer.h, common/darwin/Classes/FlutterRTCFrameCapturer.m
Rewrote code for frame capture.
Added support for MacOS.
Also now saves JPEG/PNG data depending on file extension.
=> Frame capture support for MacOS

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java
add enableCpuOveruseDetection configuration
=> add enableCpuOveruseDetection configuration

common/darwin/Classes/FlutterWebRTCPlugin.m
Should fix [#1180](https://github.com/flutter-webrtc/flutter-webrtc/issues/1180)
=> Implement detachFromEngineForRegistrar

lib/src/native/rtc_rtp_receiver_impl.dart, lib/src/native/rtc_rtp_sender_impl.dart
change  "getstats" parameter  'track' to 'trackId'
=> bugfix  getStats  with wrong parameter name

android/src/main/java/com/cloudwebrtc/webrtc/audio/AudioSwitchManager.java
The problem:
No output devices are available unless a user media stream is created due to the switch manager not being present before the audio manager is started.
The solution:
Initialize and start the switch manager and only activate it when needed.
=> Start audioswitch and only activate it when needed

android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java
Solves the captureFrame part of #1176
=> Fixed frame capturer returning images with wrong colors

example/lib/main.dart, example/lib/src/get_user_media_sample_web.dart, example/lib/src/loopback_sample_unified_tracks.dart, lib/src/web/rtc_video_renderer_impl.dart, lib/src/web/rtc_video_view_impl.dart
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1038
The reason is that Transform Widgets are not successfully applied to the local video, changing to `element.style.transform = 'scaleX(-1)';` to fixed
=> fix video renderer issue for safari.

android/build.gradle
=> Switch to webrtc 104.5112.07 hosted on maven central

common/cpp/include/flutter_peerconnection.h, common/cpp/include/flutter_webrtc_base.h, common/cpp/src/flutter_media_stream.cc, common/cpp/src/flutter_peerconnection.cc, common/cpp/src/flutter_webrtc.cc, example/lib/src/loopback_sample_unified_tracks.dart, third_party/libwebrtc/include/rtc_rtp_transceiver.h, third_party/libwebrtc/include/rtc_video_device.h
* use the correct transceiver id
* and support restart camera.
=> chore: general fixes for win/linux.

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/audio/AudioSwitchManager.java, common/darwin/Classes/AudioUtils.m, common/darwin/Classes/FlutterWebRTCPlugin.m, lib/src/helper.dart
Would be great if someone can test this on ios, not completely sure about that part. Android works as expected
interface PR: https://github.com/flutter-webrtc/webrtc-interface/pull/17
=> feat: add way to enable speaker but prefer bluetooth

common/cpp/include/flutter_peerconnection.h, common/cpp/src/flutter_peerconnection.cc, common/cpp/src/flutter_webrtc.cc
Fix the crash issue https://github.com/flutter-webrtc/flutter-webrtc/issues/1342
=> Fix the crash issue of video room

android/build.gradle, android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, common/darwin/Classes/FlutterRTCMediaStream.m, ios/flutter_webrtc.podspec, macos/flutter_webrtc.podspec, third_party/libwebrtc/include/rtc_audio_track.h, third_party/libwebrtc/include/rtc_frame_cryptor.h, third_party/libwebrtc/include/rtc_rtp_transceiver.h
=> update libwebrtc to m114.

common/darwin/Classes/FlutterRTCDesktopCapturer.m, common/darwin/Classes/FlutterRTCFrameCapturer.m, common/darwin/Classes/FlutterRTCFrameCryptor.h, common/darwin/Classes/FlutterRTCFrameCryptor.m, common/darwin/Classes/FlutterRTCMediaStream.h, common/darwin/Classes/FlutterRTCMediaStream.m
=> fix: compiler warning for darwin

android/build.gradle, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/audio/AudioSwitchManager.java, lib/flutter_webrtc.dart, lib/src/helper.dart, lib/src/native/android/audio_configuration.dart
default audio modes is also changed from MODE_IN_COMMUNICATION to MODE_NORMAL.
=> feat: expose android audio modes

lib/src/native/rtc_video_view_impl.dart
Reverts flutter-webrtc/flutter-webrtc#1406
=> Revert "Partially rebuild RTCVideoView when renderVideo value changes"

lib/src/helper.dart
there was an error in documentation
=> fixed documentation

common/darwin/Classes/FlutterRTCDataChannel.m, common/darwin/Classes/FlutterRTCDesktopCapturer.m, common/darwin/Classes/FlutterRTCFrameCryptor.m, common/darwin/Classes/FlutterRTCPeerConnection.m, common/darwin/Classes/FlutterRTCVideoRenderer.m, common/darwin/Classes/FlutterWebRTCPlugin.h, common/darwin/Classes/FlutterWebRTCPlugin.m
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1428
=> fix: send message on non-platform thread.

android/build.gradle
Updates AudioSwitch lib to fix this issue.
=> Fix bluetooth sco not stopping after all peer connections disconnect

common/darwin/Classes/FlutterWebRTCPlugin.m, lib/src/helper.dart, lib/src/native/audio_management.dart
Sometimes this needs to be called manually when changing the audioSession configuration with a 3rd party plugin.
=> Supports ensureAudioSsession method for iOS only.

common/cpp/include/flutter_common.h, common/cpp/src/flutter_webrtc.cc
Allows setting volume for audio tracks.
=> feat(windows): setVolume for audio track

CHANGELOG.md, lib/src/web/rtc_video_renderer_impl.dart, lib/src/web/rtc_video_view_impl.dart, pubspec.yaml
fixes #1545 
see also:
https://github.com/flutter-webrtc/dart-webrtc/pull/29
=> move to package:web

common/darwin/Classes/FlutterRTCFrameCapturer.m, common/darwin/Classes/FlutterRTCVideoRenderer.m, ios/flutter_webrtc.podspec, macos/flutter_webrtc.podspec
note: includes the privacy manifest for the webrtc frameworks
=> chore: update swift webrtc sdks to 114.5735.10

example/pubspec.yaml
STATUS: Ready for review
---
Updates the example environment to match the environment that is used by the `package:flutter_webrtc`:
https://github.com/flutter-webrtc/flutter-webrtc/blob/21f42a1bc2c397f686120abf5b31c13906ce744e/pubspec.yaml#L6
=> chore: update example environment

common/darwin/Classes/FlutterRTCVideoRenderer.m
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1441
=> fix: Memory leak for Darwin.

README.md
The current link is not available
=> [Docs] Fixing proguard rules link

lib/src/native/rtc_video_renderer_impl.dart
While dart is single threaded, async code can still run concurrently. Execution can be yielded at any usage of `await`. This means that, when calling renderer.initialize twice in relatively short amount of time, it will allocate two textures, but only free one of them.
This commit fixes this by atomically (no `await` in between) checking and setting an initialization completer.
The completer will wait for pending initializations or (more likely) return immediately if already initialized
=> fix: race condition during video renderer initialization

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java
This allows accessing facing mode from track settings even if camera was selected by ID or other constraints
=> feat: set facing mode after selecting camera

Documentation/E2EE.md
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1724
=> docs: E2EE doc.

lib/src/native/rtc_video_platform_view_controller.dart, lib/src/native/rtc_video_renderer_impl.dart, lib/src/web/rtc_video_renderer_impl.dart
depends on https://github.com/flutter-webrtc/webrtc-interface/pull/30
=> feat: expose rtc video value

android/src/main/AndroidManifest.xml, android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java
fix: https://github.com/flutter-webrtc/flutter-webrtc/issues/1648
=> Remove V1 plugin

lib/src/native/media_stream_track_impl.dart, pubspec.yaml
selectAudioOutput and selectAudioInput methods created to enable dynamic change on audio intput/output device
=> Updated MediaStreamTrackNative

android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java, common/cpp/include/flutter_data_channel.h, common/cpp/src/flutter_data_channel.cc, common/cpp/src/flutter_webrtc.cc, common/darwin/Classes/FlutterRTCDataChannel.h, common/darwin/Classes/FlutterRTCDataChannel.m, common/darwin/Classes/FlutterWebRTCPlugin.m, example/lib/src/loopback_data_channel_sample.dart, lib/src/native/rtc_data_channel_impl.dart, pubspec.yaml, third_party/libwebrtc/include/rtc_data_channel.h, third_party/libwebrtc/include/rtc_ice_transport.h
Add getBufferedAmount method to get the current buffered amount value from native DC
=> feat: add getBufferedAmount for DataChannel.

android/src/main/java/com/cloudwebrtc/webrtc/SurfaceTextureRenderer.java
fix: Migrate from onSurfaceDestroyed to onSurfaceCleanup for SurfaceProducer.Callback.
=> fix: Migrate from onSurfaceDestroyed to onSurfaceCleanup

linux/CMakeLists.txt, linux/flutter_webrtc_plugin.cc, linux/task_runner_linux.cc, linux/task_runner_linux.h
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1820,
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1674,
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1580,
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1465
=> fix: add task runner for linux.

android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java, android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java, common/darwin/Classes/FlutterRTCAudioSink-Interface.h, common/darwin/Classes/FlutterRTCAudioSink.h, common/darwin/Classes/FlutterRTCAudioSink.mm, common/darwin/Classes/FlutterRTCFrameCapturer.h, common/darwin/Classes/FlutterRTCFrameCapturer.m, common/darwin/Classes/FlutterRTCMediaRecorder.h, common/darwin/Classes/FlutterRTCMediaRecorder.m, common/darwin/Classes/FlutterWebRTCPlugin.h, common/darwin/Classes/FlutterWebRTCPlugin.m, common/darwin/Classes/RTCAudioSource+Private.h, common/darwin/Classes/audio_sink_bridge.cpp, common/darwin/Classes/media_stream_interface.h, example/lib/src/get_user_media_sample.dart, example/pubspec.yaml, ios/Classes/FlutterRTCAudioSink-Interface.h, ios/Classes/FlutterRTCAudioSink.h, ios/Classes/FlutterRTCAudioSink.mm, ios/Classes/FlutterRTCMediaRecorder.h, ios/Classes/FlutterRTCMediaRecorder.m, ios/Classes/RTCAudioSource+Private.h, ios/Classes/audio_sink_bridge.cpp, ios/Classes/media_stream_interface.h, ios/flutter_webrtc.podspec, lib/src/media_recorder.dart, lib/src/native/media_recorder_impl.dart, pubspec.yaml
Reverts flutter-webrtc/flutter-webrtc#1822
=> feat: Media Recorder implementation Android and iOS

ios/flutter_webrtc.podspec, macos/flutter_webrtc.podspec
- Fix deadlock when creating a frame cryptor on iOS/macOS.
=> bump version for WebRTC.framework.

android/src/main/java/com/cloudwebrtc/webrtc/record/VideoFileRenderer.java
I found that it crashes when I stop recording.
=> Recording bug

android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, example/lib/src/loopback_sample_unified_tracks.dart, ios/flutter_webrtc.podspec, macos/flutter_webrtc.podspec
close https://github.com/flutter-webrtc/flutter-webrtc/issues/1899
=> bump libwebrtc to 137.7151.03.
